/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../../app/routes/__root'
import { Route as DashboardLayoutRouteImport } from './../../../app/routes/dashboard/layout'
import { Route as IndexRouteImport } from './../../../app/routes/index'
import { Route as DashboardIndexRouteImport } from './../../../app/routes/dashboard/index'
import { Route as DashboardBoardIdRouteImport } from './../../../app/routes/dashboard/$boardId'
import { Route as AuthAuthLayoutRouteImport } from './../../../app/routes/auth/_auth-layout'
import { Route as DashboardSettingsLayoutRouteImport } from './../../../app/routes/dashboard/settings/layout'
import { Route as DashboardSettingsIndexRouteImport } from './../../../app/routes/dashboard/settings/index'
import { Route as DashboardSettingsTaskRouteImport } from './../../../app/routes/dashboard/settings/task'
import { Route as DashboardSettingsGeneralRouteImport } from './../../../app/routes/dashboard/settings/general'
import { Route as DashboardSettingsAccessibilityRouteImport } from './../../../app/routes/dashboard/settings/accessibility'
import { Route as AuthAuthLayoutSignupRouteImport } from './../../../app/routes/auth/_auth-layout.signup'
import { Route as AuthAuthLayoutSigninRouteImport } from './../../../app/routes/auth/_auth-layout.signin'

const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardBoardIdRoute = DashboardBoardIdRouteImport.update({
  id: '/$boardId',
  path: '/$boardId',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const AuthAuthLayoutRoute = AuthAuthLayoutRouteImport.update({
  id: '/auth/_auth-layout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsLayoutRoute = DashboardSettingsLayoutRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsLayoutRoute,
} as any)
const DashboardSettingsTaskRoute = DashboardSettingsTaskRouteImport.update({
  id: '/task',
  path: '/task',
  getParentRoute: () => DashboardSettingsLayoutRoute,
} as any)
const DashboardSettingsGeneralRoute =
  DashboardSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => DashboardSettingsLayoutRoute,
  } as any)
const DashboardSettingsAccessibilityRoute =
  DashboardSettingsAccessibilityRouteImport.update({
    id: '/accessibility',
    path: '/accessibility',
    getParentRoute: () => DashboardSettingsLayoutRoute,
  } as any)
const AuthAuthLayoutSignupRoute = AuthAuthLayoutSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)
const AuthAuthLayoutSigninRoute = AuthAuthLayoutSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsLayoutRouteWithChildren
  '/auth': typeof AuthAuthLayoutRouteWithChildren
  '/dashboard/$boardId': typeof DashboardBoardIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/signin': typeof AuthAuthLayoutSigninRoute
  '/auth/signup': typeof AuthAuthLayoutSignupRoute
  '/dashboard/settings/accessibility': typeof DashboardSettingsAccessibilityRoute
  '/dashboard/settings/general': typeof DashboardSettingsGeneralRoute
  '/dashboard/settings/task': typeof DashboardSettingsTaskRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthAuthLayoutRouteWithChildren
  '/dashboard/$boardId': typeof DashboardBoardIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/signin': typeof AuthAuthLayoutSigninRoute
  '/auth/signup': typeof AuthAuthLayoutSignupRoute
  '/dashboard/settings/accessibility': typeof DashboardSettingsAccessibilityRoute
  '/dashboard/settings/general': typeof DashboardSettingsGeneralRoute
  '/dashboard/settings/task': typeof DashboardSettingsTaskRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsLayoutRouteWithChildren
  '/auth/_auth-layout': typeof AuthAuthLayoutRouteWithChildren
  '/dashboard/$boardId': typeof DashboardBoardIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/_auth-layout/signin': typeof AuthAuthLayoutSigninRoute
  '/auth/_auth-layout/signup': typeof AuthAuthLayoutSignupRoute
  '/dashboard/settings/accessibility': typeof DashboardSettingsAccessibilityRoute
  '/dashboard/settings/general': typeof DashboardSettingsGeneralRoute
  '/dashboard/settings/task': typeof DashboardSettingsTaskRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/settings'
    | '/auth'
    | '/dashboard/$boardId'
    | '/dashboard/'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/settings/accessibility'
    | '/dashboard/settings/general'
    | '/dashboard/settings/task'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/$boardId'
    | '/dashboard'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/settings/accessibility'
    | '/dashboard/settings/general'
    | '/dashboard/settings/task'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/settings'
    | '/auth/_auth-layout'
    | '/dashboard/$boardId'
    | '/dashboard/'
    | '/auth/_auth-layout/signin'
    | '/auth/_auth-layout/signup'
    | '/dashboard/settings/accessibility'
    | '/dashboard/settings/general'
    | '/dashboard/settings/task'
    | '/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  AuthAuthLayoutRoute: typeof AuthAuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/$boardId': {
      id: '/dashboard/$boardId'
      path: '/$boardId'
      fullPath: '/dashboard/$boardId'
      preLoaderRoute: typeof DashboardBoardIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/auth/_auth-layout': {
      id: '/auth/_auth-layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsLayoutRoute
    }
    '/dashboard/settings/task': {
      id: '/dashboard/settings/task'
      path: '/task'
      fullPath: '/dashboard/settings/task'
      preLoaderRoute: typeof DashboardSettingsTaskRouteImport
      parentRoute: typeof DashboardSettingsLayoutRoute
    }
    '/dashboard/settings/general': {
      id: '/dashboard/settings/general'
      path: '/general'
      fullPath: '/dashboard/settings/general'
      preLoaderRoute: typeof DashboardSettingsGeneralRouteImport
      parentRoute: typeof DashboardSettingsLayoutRoute
    }
    '/dashboard/settings/accessibility': {
      id: '/dashboard/settings/accessibility'
      path: '/accessibility'
      fullPath: '/dashboard/settings/accessibility'
      preLoaderRoute: typeof DashboardSettingsAccessibilityRouteImport
      parentRoute: typeof DashboardSettingsLayoutRoute
    }
    '/auth/_auth-layout/signup': {
      id: '/auth/_auth-layout/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthAuthLayoutSignupRouteImport
      parentRoute: typeof AuthAuthLayoutRoute
    }
    '/auth/_auth-layout/signin': {
      id: '/auth/_auth-layout/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthAuthLayoutSigninRouteImport
      parentRoute: typeof AuthAuthLayoutRoute
    }
  }
}

interface DashboardSettingsLayoutRouteChildren {
  DashboardSettingsAccessibilityRoute: typeof DashboardSettingsAccessibilityRoute
  DashboardSettingsGeneralRoute: typeof DashboardSettingsGeneralRoute
  DashboardSettingsTaskRoute: typeof DashboardSettingsTaskRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsLayoutRouteChildren: DashboardSettingsLayoutRouteChildren =
  {
    DashboardSettingsAccessibilityRoute: DashboardSettingsAccessibilityRoute,
    DashboardSettingsGeneralRoute: DashboardSettingsGeneralRoute,
    DashboardSettingsTaskRoute: DashboardSettingsTaskRoute,
    DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  }

const DashboardSettingsLayoutRouteWithChildren =
  DashboardSettingsLayoutRoute._addFileChildren(
    DashboardSettingsLayoutRouteChildren,
  )

interface DashboardLayoutRouteChildren {
  DashboardSettingsLayoutRoute: typeof DashboardSettingsLayoutRouteWithChildren
  DashboardBoardIdRoute: typeof DashboardBoardIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardSettingsLayoutRoute: DashboardSettingsLayoutRouteWithChildren,
  DashboardBoardIdRoute: DashboardBoardIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface AuthAuthLayoutRouteChildren {
  AuthAuthLayoutSigninRoute: typeof AuthAuthLayoutSigninRoute
  AuthAuthLayoutSignupRoute: typeof AuthAuthLayoutSignupRoute
}

const AuthAuthLayoutRouteChildren: AuthAuthLayoutRouteChildren = {
  AuthAuthLayoutSigninRoute: AuthAuthLayoutSigninRoute,
  AuthAuthLayoutSignupRoute: AuthAuthLayoutSignupRoute,
}

const AuthAuthLayoutRouteWithChildren = AuthAuthLayoutRoute._addFileChildren(
  AuthAuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  AuthAuthLayoutRoute: AuthAuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
