/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './../../../app/routes/__root'
import { Route as IndexImport } from './../../../app/routes/index'
import { Route as dashboardDashboardImport } from './../../../app/routes/(dashboard)/dashboard'
import { Route as authAuthLayoutImport } from './../../../app/routes/(auth)/_auth-layout'
import { Route as dashboardDashboardIndexImport } from './../../../app/routes/(dashboard)/dashboard.index'
import { Route as dashboardDashboardBoardIdImport } from './../../../app/routes/(dashboard)/dashboard.$boardId'
import { Route as authAuthLayoutSignupImport } from './../../../app/routes/(auth)/_auth-layout.signup'
import { Route as authAuthLayoutSigninImport } from './../../../app/routes/(auth)/_auth-layout.signin'

// Create Virtual Routes

const authImport = createFileRoute('/(auth)')()

// Create/Update Routes

const authRoute = authImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute
} as any)

const dashboardDashboardRoute = dashboardDashboardImport.update({
  id: '/(dashboard)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute
} as any)

const authAuthLayoutRoute = authAuthLayoutImport.update({
  id: '/_auth-layout',
  getParentRoute: () => authRoute
} as any)

const dashboardDashboardIndexRoute = dashboardDashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardDashboardRoute
} as any)

const dashboardDashboardBoardIdRoute = dashboardDashboardBoardIdImport.update({
  id: '/$boardId',
  path: '/$boardId',
  getParentRoute: () => dashboardDashboardRoute
} as any)

const authAuthLayoutSignupRoute = authAuthLayoutSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authAuthLayoutRoute
} as any)

const authAuthLayoutSigninRoute = authAuthLayoutSigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => authAuthLayoutRoute
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/_auth-layout': {
      id: '/(auth)/_auth-layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authAuthLayoutImport
      parentRoute: typeof authRoute
    }
    '/(dashboard)/dashboard': {
      id: '/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardDashboardImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/_auth-layout/signin': {
      id: '/(auth)/_auth-layout/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authAuthLayoutSigninImport
      parentRoute: typeof authAuthLayoutImport
    }
    '/(auth)/_auth-layout/signup': {
      id: '/(auth)/_auth-layout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authAuthLayoutSignupImport
      parentRoute: typeof authAuthLayoutImport
    }
    '/(dashboard)/dashboard/$boardId': {
      id: '/(dashboard)/dashboard/$boardId'
      path: '/$boardId'
      fullPath: '/dashboard/$boardId'
      preLoaderRoute: typeof dashboardDashboardBoardIdImport
      parentRoute: typeof dashboardDashboardImport
    }
    '/(dashboard)/dashboard/': {
      id: '/(dashboard)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof dashboardDashboardIndexImport
      parentRoute: typeof dashboardDashboardImport
    }
  }
}

// Create and export the route tree

interface authAuthLayoutRouteChildren {
  authAuthLayoutSigninRoute: typeof authAuthLayoutSigninRoute
  authAuthLayoutSignupRoute: typeof authAuthLayoutSignupRoute
}

const authAuthLayoutRouteChildren: authAuthLayoutRouteChildren = {
  authAuthLayoutSigninRoute: authAuthLayoutSigninRoute,
  authAuthLayoutSignupRoute: authAuthLayoutSignupRoute
}

const authAuthLayoutRouteWithChildren = authAuthLayoutRoute._addFileChildren(
  authAuthLayoutRouteChildren
)

interface authRouteChildren {
  authAuthLayoutRoute: typeof authAuthLayoutRouteWithChildren
}

const authRouteChildren: authRouteChildren = {
  authAuthLayoutRoute: authAuthLayoutRouteWithChildren
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

interface dashboardDashboardRouteChildren {
  dashboardDashboardBoardIdRoute: typeof dashboardDashboardBoardIdRoute
  dashboardDashboardIndexRoute: typeof dashboardDashboardIndexRoute
}

const dashboardDashboardRouteChildren: dashboardDashboardRouteChildren = {
  dashboardDashboardBoardIdRoute: dashboardDashboardBoardIdRoute,
  dashboardDashboardIndexRoute: dashboardDashboardIndexRoute
}

const dashboardDashboardRouteWithChildren =
  dashboardDashboardRoute._addFileChildren(dashboardDashboardRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof authAuthLayoutRouteWithChildren
  '/dashboard': typeof dashboardDashboardRouteWithChildren
  '/signin': typeof authAuthLayoutSigninRoute
  '/signup': typeof authAuthLayoutSignupRoute
  '/dashboard/$boardId': typeof dashboardDashboardBoardIdRoute
  '/dashboard/': typeof dashboardDashboardIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof authAuthLayoutRouteWithChildren
  '/signin': typeof authAuthLayoutSigninRoute
  '/signup': typeof authAuthLayoutSignupRoute
  '/dashboard/$boardId': typeof dashboardDashboardBoardIdRoute
  '/dashboard': typeof dashboardDashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteWithChildren
  '/(auth)/_auth-layout': typeof authAuthLayoutRouteWithChildren
  '/(dashboard)/dashboard': typeof dashboardDashboardRouteWithChildren
  '/(auth)/_auth-layout/signin': typeof authAuthLayoutSigninRoute
  '/(auth)/_auth-layout/signup': typeof authAuthLayoutSignupRoute
  '/(dashboard)/dashboard/$boardId': typeof dashboardDashboardBoardIdRoute
  '/(dashboard)/dashboard/': typeof dashboardDashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/dashboard/$boardId'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/signup' | '/dashboard/$boardId' | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(auth)/_auth-layout'
    | '/(dashboard)/dashboard'
    | '/(auth)/_auth-layout/signin'
    | '/(auth)/_auth-layout/signup'
    | '/(dashboard)/dashboard/$boardId'
    | '/(dashboard)/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRoute: typeof authRouteWithChildren
  dashboardDashboardRoute: typeof dashboardDashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRoute: authRouteWithChildren,
  dashboardDashboardRoute: dashboardDashboardRouteWithChildren
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(auth)",
        "/(dashboard)/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(auth)": {
      "filePath": "(auth)",
      "children": [
        "/(auth)/_auth-layout"
      ]
    },
    "/(auth)/_auth-layout": {
      "filePath": "(auth)/_auth-layout.tsx",
      "parent": "/(auth)",
      "children": [
        "/(auth)/_auth-layout/signin",
        "/(auth)/_auth-layout/signup"
      ]
    },
    "/(dashboard)/dashboard": {
      "filePath": "(dashboard)/dashboard.tsx",
      "children": [
        "/(dashboard)/dashboard/$boardId",
        "/(dashboard)/dashboard/"
      ]
    },
    "/(auth)/_auth-layout/signin": {
      "filePath": "(auth)/_auth-layout.signin.tsx",
      "parent": "/(auth)/_auth-layout"
    },
    "/(auth)/_auth-layout/signup": {
      "filePath": "(auth)/_auth-layout.signup.tsx",
      "parent": "/(auth)/_auth-layout"
    },
    "/(dashboard)/dashboard/$boardId": {
      "filePath": "(dashboard)/dashboard.$boardId.tsx",
      "parent": "/(dashboard)/dashboard"
    },
    "/(dashboard)/dashboard/": {
      "filePath": "(dashboard)/dashboard.index.tsx",
      "parent": "/(dashboard)/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
