/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as authAuthLayoutImport } from './routes/(auth)/_auth-layout'
import { Route as authAuthLayoutSigninImport } from './routes/(auth)/_auth-layout.signin'
import { Route as authAuthLayoutSignupImport } from './routes/(auth)/_auth-layout.signup'
import { Route as workspaceDashboardImport } from './routes/(workspace)/dashboard'
import { Route as workspaceDashboardBoardIdImport } from './routes/(workspace)/dashboard/$boardId'
import { Route as workspaceDashboardIndexImport } from './routes/(workspace)/dashboard/index'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const authImport = createFileRoute('/(auth)')()

// Create/Update Routes

const authRoute = authImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute
} as any)

const workspaceDashboardRoute = workspaceDashboardImport.update({
  id: '/(workspace)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute
} as any)

const authAuthLayoutRoute = authAuthLayoutImport.update({
  id: '/_auth-layout',
  getParentRoute: () => authRoute
} as any)

const workspaceDashboardIndexRoute = workspaceDashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => workspaceDashboardRoute
} as any)

const workspaceDashboardBoardIdRoute = workspaceDashboardBoardIdImport.update({
  id: '/$boardId',
  path: '/$boardId',
  getParentRoute: () => workspaceDashboardRoute
} as any)

const authAuthLayoutSignupRoute = authAuthLayoutSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authAuthLayoutRoute
} as any)

const authAuthLayoutSigninRoute = authAuthLayoutSigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => authAuthLayoutRoute
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/_auth-layout': {
      id: '/(auth)/_auth-layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authAuthLayoutImport
      parentRoute: typeof authRoute
    }
    '/(workspace)/dashboard': {
      id: '/(workspace)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof workspaceDashboardImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/_auth-layout/signin': {
      id: '/(auth)/_auth-layout/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authAuthLayoutSigninImport
      parentRoute: typeof authAuthLayoutImport
    }
    '/(auth)/_auth-layout/signup': {
      id: '/(auth)/_auth-layout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authAuthLayoutSignupImport
      parentRoute: typeof authAuthLayoutImport
    }
    '/(workspace)/dashboard/$boardId': {
      id: '/(workspace)/dashboard/$boardId'
      path: '/$boardId'
      fullPath: '/dashboard/$boardId'
      preLoaderRoute: typeof workspaceDashboardBoardIdImport
      parentRoute: typeof workspaceDashboardImport
    }
    '/(workspace)/dashboard/': {
      id: '/(workspace)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof workspaceDashboardIndexImport
      parentRoute: typeof workspaceDashboardImport
    }
  }
}

// Create and export the route tree

interface authAuthLayoutRouteChildren {
  authAuthLayoutSigninRoute: typeof authAuthLayoutSigninRoute
  authAuthLayoutSignupRoute: typeof authAuthLayoutSignupRoute
}

const authAuthLayoutRouteChildren: authAuthLayoutRouteChildren = {
  authAuthLayoutSigninRoute: authAuthLayoutSigninRoute,
  authAuthLayoutSignupRoute: authAuthLayoutSignupRoute
}

const authAuthLayoutRouteWithChildren = authAuthLayoutRoute._addFileChildren(
  authAuthLayoutRouteChildren
)

interface authRouteChildren {
  authAuthLayoutRoute: typeof authAuthLayoutRouteWithChildren
}

const authRouteChildren: authRouteChildren = {
  authAuthLayoutRoute: authAuthLayoutRouteWithChildren
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

interface workspaceDashboardRouteChildren {
  workspaceDashboardBoardIdRoute: typeof workspaceDashboardBoardIdRoute
  workspaceDashboardIndexRoute: typeof workspaceDashboardIndexRoute
}

const workspaceDashboardRouteChildren: workspaceDashboardRouteChildren = {
  workspaceDashboardBoardIdRoute: workspaceDashboardBoardIdRoute,
  workspaceDashboardIndexRoute: workspaceDashboardIndexRoute
}

const workspaceDashboardRouteWithChildren =
  workspaceDashboardRoute._addFileChildren(workspaceDashboardRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof authAuthLayoutRouteWithChildren
  '/dashboard': typeof workspaceDashboardRouteWithChildren
  '/signin': typeof authAuthLayoutSigninRoute
  '/signup': typeof authAuthLayoutSignupRoute
  '/dashboard/$boardId': typeof workspaceDashboardBoardIdRoute
  '/dashboard/': typeof workspaceDashboardIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof authAuthLayoutRouteWithChildren
  '/signin': typeof authAuthLayoutSigninRoute
  '/signup': typeof authAuthLayoutSignupRoute
  '/dashboard/$boardId': typeof workspaceDashboardBoardIdRoute
  '/dashboard': typeof workspaceDashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteWithChildren
  '/(auth)/_auth-layout': typeof authAuthLayoutRouteWithChildren
  '/(workspace)/dashboard': typeof workspaceDashboardRouteWithChildren
  '/(auth)/_auth-layout/signin': typeof authAuthLayoutSigninRoute
  '/(auth)/_auth-layout/signup': typeof authAuthLayoutSignupRoute
  '/(workspace)/dashboard/$boardId': typeof workspaceDashboardBoardIdRoute
  '/(workspace)/dashboard/': typeof workspaceDashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/dashboard/$boardId'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/signup' | '/dashboard/$boardId' | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(auth)/_auth-layout'
    | '/(workspace)/dashboard'
    | '/(auth)/_auth-layout/signin'
    | '/(auth)/_auth-layout/signup'
    | '/(workspace)/dashboard/$boardId'
    | '/(workspace)/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRoute: typeof authRouteWithChildren
  workspaceDashboardRoute: typeof workspaceDashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRoute: authRouteWithChildren,
  workspaceDashboardRoute: workspaceDashboardRouteWithChildren
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(auth)",
        "/(workspace)/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(auth)": {
      "filePath": "(auth)",
      "children": [
        "/(auth)/_auth-layout"
      ]
    },
    "/(auth)/_auth-layout": {
      "filePath": "(auth)/_auth-layout.tsx",
      "parent": "/(auth)",
      "children": [
        "/(auth)/_auth-layout/signin",
        "/(auth)/_auth-layout/signup"
      ]
    },
    "/(workspace)/dashboard": {
      "filePath": "(workspace)/dashboard.tsx",
      "children": [
        "/(workspace)/dashboard/$boardId",
        "/(workspace)/dashboard/"
      ]
    },
    "/(auth)/_auth-layout/signin": {
      "filePath": "(auth)/_auth-layout.signin.tsx",
      "parent": "/(auth)/_auth-layout"
    },
    "/(auth)/_auth-layout/signup": {
      "filePath": "(auth)/_auth-layout.signup.tsx",
      "parent": "/(auth)/_auth-layout"
    },
    "/(workspace)/dashboard/$boardId": {
      "filePath": "(workspace)/dashboard/$boardId.tsx",
      "parent": "/(workspace)/dashboard"
    },
    "/(workspace)/dashboard/": {
      "filePath": "(workspace)/dashboard/index.tsx",
      "parent": "/(workspace)/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
